language: python

sudo: false

env:
    global:
        - PYTHONPATH=$PWD:$PYTHONPATH

cache:
    directories:
        - $HOME/.data

install:
    - pip install -U pip
    - pip install torch==1.4.0+cpu torchvision==0.5.0+cpu -f https://download.pytorch.org/whl/torch_stable.html

    # Keep track of Pyro dev branch
    - pip install https://github.com/pyro-ppl/pyro/archive/dev.zip

    # Keep track of pyro-api master branch
    - pip install https://github.com/pyro-ppl/pyro-api/archive/master.zip

    - pip install .[jax,test]
    - pip freeze

branches:
    only:
        - master

jobs:
    include:
        - python: 3.6
          script: make test
