language: python

sudo: false

env:
    global:
        - PYTHONPATH=$PWD:$PYTHONPATH

cache:
    directories:
        - $HOME/.data

install:
    - pip install -U pip
    - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then
          pip install https://download.pytorch.org/whl/cpu/torch-1.0.1.post2-cp27-cp27mu-linux_x86_64.whl;
      else
          pip install https://download.pytorch.org/whl/cpu/torch-1.0.1.post2-cp36-cp36m-linux_x86_64.whl;
      fi

    # Remove after public release of https://github.com/pyro-ppl/pyro/pull/1794
    - pip install https://github.com/pyro-ppl/pyro/archive/minipyro-compat.zip

    - pip install .[test]
    - pip freeze

branches:
    only:
        - master

jobs:
    include:
        - python: 2.7
          script: make test
        - python: 3.6
          script: make test
