language: python

sudo: false

env:
    global:
        - PYTHONPATH=$PWD:$PYTHONPATH

cache:
    directories:
        - $HOME/.data

install:
    - pip install -U pip

    # Keep track of pyro-api master branch
    - pip install https://github.com/pyro-ppl/pyro-api/archive/master.zip

    - pip install .[test]
    - pip freeze

branches:
    only:
        - master

jobs:
    include:
        - stage: default
          name: numpy
          python: 3.6
          script:
              - make test
        - name: torch
          python: 3.6
          script:
              - pip install torch==1.5.0+cpu torchvision==0.6.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
              # Keep track of Pyro dev branch
              - pip install https://github.com/pyro-ppl/pyro/archive/dev.zip
              - pip install -e .[torch]
              - FUNSOR_BACKEND=torch make test
        - name: jax
          python: 3.6
          script:
              # Keep track of NumPyro master branch
              - pip install https://github.com/pyro-ppl/numpyro/archive/master.zip
              - pip install -e .[jax]
              - CI=1 FUNSOR_BACKEND=jax make test
        - name: torch35
          python: 3.5
          script:
              - pip install torch==1.5.0+cpu torchvision==0.6.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
              # Keep track of Pyro dev branch
              - pip install https://github.com/pyro-ppl/pyro/archive/dev.zip
              - pip install -e .[torch]
              - FUNSOR_BACKEND=torch make test
